baseURL: "/"
title: 刘晶研究组
enableGitInfo: true
paginate: 10

# Use Wowchemy via Hugo Modules
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: [HTML, RSS, JSON]
  section: [HTML, RSS]

languages:
  zh:
    languageCode: zh-CN
    weight: 1
