locale: zh
dateFormat: 2006-01-02
description: "实验室研究方向、成员与论文发表"

features:
  # Theme appearance can be toggled by users if enabled
  appearance:
    theme_default: system
    theme_day: minimal
    theme_night: minimal

footer:
  copyright:
    notice: "© {{ year }} 实验室"

social:
  enable: true

