locale:
  date_format: 2006-01-02
description: "实验室研究方向、成员与论文发表"

features:
  appearance:
    theme_default: day
    theme_day: minimal

footer:
  copyright:
    notice: "© {{ year }} 实验室"

social:
  enable: true

marketing:
  analytics:
    google_analytics: ""
